CI : update cache and tests

diff --git a/.github/workflows/ifpen_el8_gimkl-2018b.yml b/.github/workflows/ifpen_el8_gimkl-2018b.yml
--- a/.github/workflows/ifpen_el8_gimkl-2018b.yml
+++ b/.github/workflows/ifpen_el8_gimkl-2018b.yml
@@ -94,7 +94,9 @@ jobs:
           (success() || failure()) &&
           steps.checkout.outcome == 'success'
         shell: bash
-        run: cmake -S ${{ env.ARCANE_SOURCE_DIR }} -B ${{ env.ARCANE_BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCANE_INSTALL_DIR }} ${{ env.CM_CCACHE_OPTS }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DARCCORE_BUILD_MODE=Check -DREMOVE_UID_ON_DETACH=ON -DUSE_GTEST_DEATH_TEST=ON -DCMAKE_DISABLE_FIND_PACKAGE_Papi=ON -DALIEN_BUILD_COMPONENT=all -DALIEN_PLUGIN_HYPRE=ON -DALIEN_PLUGIN_PETSC=ON -DUSE_GRAPH_CONNECTIVITY_POLICY=ON
+        run: |
+           export CCACHE_DIR=${{ env.ARCANE_CCACHE_DIR }}
+           cmake -S ${{ env.ARCANE_SOURCE_DIR }} -B ${{ env.ARCANE_BUILD_DIR }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCANE_INSTALL_DIR }} ${{ env.CM_CCACHE_OPTS }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DARCCORE_BUILD_MODE=Check -DREMOVE_UID_ON_DETACH=ON -DUSE_GTEST_DEATH_TEST=ON -DCMAKE_DISABLE_FIND_PACKAGE_Papi=ON -DALIEN_BUILD_COMPONENT=all -DALIEN_PLUGIN_HYPRE=ON -DALIEN_PLUGIN_PETSC=ON -DUSE_GRAPH_CONNECTIVITY_POLICY=ON
 
       - name: Build
         id: build
@@ -104,13 +106,13 @@ jobs:
         shell: bash
         run: cmake --build ${{ env.ARCANE_BUILD_DIR }} ${{ env.CM_BUILD_OPTS }}
 
-      - name: Clean
-        id: clean
-        if: |
-          (success() || failure()) &&
-          steps.build.outcome == 'success'
-        shell: bash
-        run: find ${{ env.ARCANE_BUILD_DIR }} -type f -name '*.o' -exec rm -f '{}' \;
+      #- name: Clean
+      #  id: clean
+      #  if: |
+      #    (success() || failure()) &&
+      #    steps.build.outcome == 'success'
+      #  shell: bash
+      #  run: find ${{ env.ARCANE_BUILD_DIR }} -type f -name '*.o' -exec rm -f '{}' \;
 
       - name: Install
         id: install
